# Generated by Django 4.1.1 on 2022-09-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='')),
                ('type', models.CharField(choices=[('HEART', 'HEART'), ('KIDNEYS', 'KIDNEYS'), ('LIVER', 'LIVER'), ('EYES', 'EYES')], max_length=100)),
                ('timeadd', models.DateTimeField()),
            ],
        ),
    ]
